import { Layout } from "@/components/layout/Layout";
import { PageHeading } from "@/components/ui/PageHeading";
import { currentUser } from "@/data/mockData";

export default function Leads() {
  return (
    <Layout activeTab="leads" user={currentUser} notificationCount={1}>
      <div className="flex flex-col gap-8">
        <PageHeading
          title="Leads"
          subtitle="Track and manage leads generated by your AI agents"
        />
        <div className="bg-white rounded-lg p-8 flex items-center justify-center min-h-[400px]">
          <p className="text-[var(--color-text-light)]">
            Leads management interface coming soon...
          </p>
        </div>
      </div>
    </Layout>
  );
}
